### PR TITLE
Support other Multi-Config generators with Debug.

### PR DESCRIPTION
**Pull request by hwhsu1231**
Try to fix: #113

### CODE REVIEW

**Comment by jtsiomb** [comment]
Interesting. `GENERATOR_IS_MULTI_CONFIG` is only available from cmake 3.9. If I'm reading the cmake docs correctly, older versions of cmake which don't have that property will just return `NOTFOUND` which I'm not sure what it does when fed to that IF. We should handle that case properly, and fallback to the old logic if that happens.

**Review by jtsiomb — CHANGES_REQUESTED** [review]
`GENERATOR_IS_MULTI_CONFIG` is only available from cmake 3.9. If I'm reading the cmake docs correctly, older versions of cmake which don't have that property will just return `NOTFOUND` which I'm not sure what it does when fed to that `IF`. We should handle that case properly, and fallback to the old logic if that happens.

**Comment by hwhsu1231** [comment]
@jtsiomb 

I posted a workaround compatible before CMake 3.9.

**Review by jtsiomb — APPROVED** [review]

**Comment by jtsiomb** [comment]
Alright, this is clearly not a perfect solution, but it does the job while retaining backwards compatibilitiy to older versions of cmake, so I'll go ahead and merge it. Thank you.

**Pull request merged**
