### PR TITLE
Make some files work in a single unit build

### PR DESCRIPTION
**Pull request by j0ng4b**

### CODE REVIEW

**Comment by rcmaniac25** [comment]
Looks fine to me, though the change in `src/mswin/fg_input_devices_mswin.c` is not necessary for this (and maybe reference/restate the ticket from earlier so there's some knowledge of what this is and why if they never saw the ticket)

But let @jtsiomb check it off

**Comment by j0ng4b** [comment]
> Looks fine to me, though the change in `src/mswin/fg_input_devices_mswin.c` is not necessary for this (and maybe reference/restate the ticket from earlier so there's some knowledge of what this is and why if they never saw the ticket)

Yes, the changes was because the compiler complains about this line: https://github.com/FreeGLUTProject/freeglut/blob/1c4d16c72345acaa80ef91480a49ca7372165abd/src/fg_input_devices.c#L33-L35

in `src/mswin/fg_input_devices_mswin.c` `SERIALPORT` is redefined here as a diffent symbol https://github.com/FreeGLUTProject/freeglut/blob/1c4d16c72345acaa80ef91480a49ca7372165abd/src/mswin/fg_input_devices_mswin.c#L34-L38

**Comment by jtsiomb** [comment]
This is a messy pull request. There are a number of commits here which have already being merged, and a number of irrelevant "warning fixes". It looks like only part of commit 2e88288 is relevant.

Let's keep it simple and do one thing at a time, please rebase your changes to the current master branch and submit a new pull request with *only* the fixes required for building as a single unit. No consts to chase warnings around, and no adding pointless extern keywords in front of function prototypes.

The changes to the font files and the mswin serialport structure seems fine to me.

**Comment by j0ng4b** [comment]
> This is a messy pull request. There are a number of commits here which have already being merged, and a number of irrelevant "warning fixes". It looks like only part of commit [2e88288](https://github.com/FreeGLUTProject/freeglut/commit/2e88288e8805cec1739be9e63fc11019bf9f0558) is relevant.
> 
> Let's keep it simple and do one thing at a time, please rebase your changes to the current master branch and submit a new pull request with _only_ the fixes required for building as a single unit. 

My fault, I'll keep this in mind next times.

> No consts to chase warnings around, and no adding pointless extern keywords in front of function prototypes.

When I tried to build again I see the extern keywords its really pointless. The const is used to fix error of 'conflicting type qualifiers'.

> Edit: if you'd rather not re-submit, and assuming I identified correctly which parts are relevant, I could export commit [2e88288](https://github.com/FreeGLUTProject/freeglut/commit/2e88288e8805cec1739be9e63fc11019bf9f0558) as a patch, modify it to remove irrelevant bits and apply it manually, if you prefer.

Seems okay to me.

**Comment by jtsiomb** [comment]
Merged relevant parts manually.

**Pull request closed without merging**
